function XmlFileWriter(environment)
{
    this.environment = environment;
}

XmlFileWriter.prototype.writeAssetXml = function(assetMap)
{
    var assetXml = this.generateAssetXml(assetMap);
    var xmlPath = this.environment.xmlFolderPath + "/" + this.environment.psdName + ".xml";
    this.writeXmlFile(xmlPath, assetXml);
}

XmlFileWriter.prototype.generateAssetXml = function(assetMap)
{
    var assetXml = "<!-- 由PSD2UGUI工具自动生成(Auto Generated By PSD2UGUI) -->\n";
    assetXml += "<data name=\"" + this.environment.psdName + "\">\n";
    for(var name in assetMap)
    {
        assetXml += "\t<node>" + assetMap[name] + ".png</node>\n";
    }
    assetXml += "</data>";
    return assetXml;
}

XmlFileWriter.prototype.writeXmlFile = function(path, content)
{
    var file = new File(path);
    file.encoding = "UTF8";
    if(file.open("w") == true)
    {
        file.write(content);
        file.close();
    }
}
